version: '3.3'

services:
  front:
    image: nginx
    container_name: mesatrab
    ports:
      - "80:80"
      - "443:443"
    restart: always
    expose:
      - 80
      - 443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
